<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>SoftGcc.Api</RootNamespace>
    <AssemblyName>SoftGcc.Api</AssemblyName>
    <NoWarn>CS8629;CS0472</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoftGcc.Application\SoftGcc.Application.csproj" />
    <ProjectReference Include="..\SoftGcc.Infrastructure\SoftGcc.Infrastructure.csproj" />
  </ItemGroup>

</Project>
