<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>SoftGcc.Api</RootNamespace>
    <AssemblyName>SoftGcc.Api</AssemblyName>
    <NoWarn>CS8629;CS0472</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoftGcc.Application\SoftGcc.Application.csproj" />
    <ProjectReference Include="..\SoftGcc.Infrastructure\SoftGcc.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bdd\**\*.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
