// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SoftGcc.Infrastructure.Persistence;

#nullable disable

namespace SoftGcc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824190000_AddSkillReferential")]
    partial class AddSkillReferential
    {
    }
}
